[package]
name = "ingots"
version = "0.1.0"
authors = ["Stephen M. Coakley <me@stephencoakley.com>"]

[dependencies]
log = "^0.3"

[dependencies.libloading]
version = "0.3.*"
optional = true

[features]
default = []
dynamic = ["libloading"]
